# -*- coding: utf-8 -*-
"""SMS spam/ham classification using Bag-of-Words + Naive Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNhlfPpxPZiFNAd85oCBY9pxBK-yhCpX

# SMS Spam/Ham Classification — Naive Bayes + Bag-of-Words

**Author:** David Adom Dokyi

## About Notebook

This notebook implements an SMS spam/ham classifier using a Bag-of-Words representation and a Multinomial Naive Bayes model. It includes visual evaluations (confusion matrix heatmap, reward-style learning curve) and these visuals (WordClouds, top spam keywords, misclassified samples

**Important:** Place the dataset file (named `spam.csv`) into the same folder as this notebook before running. The expected format is two columns: `label` (ham/spam) and `message`.

# Load Dataset & Plot Class Distribution

This code block loads the SMS spam/ham dataset from a CSV file named `spam.csv`. It then selects the relevant columns ('label' and 'message'), renames them for clarity, and displays the first few rows and the class distribution (count of 'ham' and 'spam' messages). The output shows a preview of the data and confirms the number of ham and spam messages, indicating a class imbalance (more ham than spam). The bar plot visualizes this imbalance.
"""

# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset (assumes the CSV is named 'spam.csv' or similar)
# For UCI SMS dataset, the file usually contains columns: ['label', 'message']
data = pd.read_csv('spam.csv', encoding='latin-1')

# Keep only the first two relevant columns and rename them
data = data.iloc[:, :2]  # selects first two columns
data.columns = ['label', 'message']

# Display first few rows
print("Sample Data Preview:")
print(data.head())

# Display dataset statistics
print("\nDataset Summary:")
print(data['label'].value_counts())

# Visualize class distribution
plt.figure(figsize=(6,4))
sns.countplot(x='label', data=data)
plt.title('Class Distribution: Ham vs Spam')
plt.xlabel('Message Type')
plt.ylabel('Count')
plt.show()

"""# Preprocessing + Bag-of-Words Vectorization

This code block preprocesses the text data and converts it into a numerical format using the Bag-of-Words (BoW) technique.
1.  It encodes the 'label' column into numerical values (0 for ham, 1 for spam) using `LabelEncoder`.
2.  It splits the dataset into training and testing sets (80% train, 20% test) using `train_test_split`, ensuring the class distribution is maintained in both sets (`stratify=data['label_encoded']`).
3.  It initializes a `CountVectorizer` to create the Bag-of-Words representation, removing common English stop words.
4.  It fits the vectorizer on the training data vocabulary and then transforms both the training and testing text messages into BoW vectors.
The output shows the shape of the resulting training and testing data matrices, where the number of columns represents the size of the vocabulary.
"""

# Import required libraries for preprocessing
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

# Encode label column (spam = 1, ham = 0)
label_encoder = LabelEncoder()
data['label_encoded'] = label_encoder.fit_transform(data['label'])

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    data['message'],
    data['label_encoded'],
    test_size=0.2,
    random_state=42,
    stratify=data['label_encoded']
)

# Initialize Bag-of-Words Vectorizer
vectorizer = CountVectorizer(stop_words='english')

# Fit on training data & transform both train and test
X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)

print("Training data shape:", X_train_bow.shape)
print("Testing data shape:", X_test_bow.shape)

"""# Train Naive Bayes & Evaluate Accuracy

This code block trains a Multinomial Naive Bayes model on the Bag-of-Words training data and evaluates its performance on the test set.
1.  It initializes a `MultinomialNB` classifier, which is suitable for text classification with count-based features.
2.  It trains the model using the `fit()` method on the training data (`X_train_bow`, `y_train`).
3.  It makes predictions on the test set (`X_test_bow`) using the `predict()` method.
4.  It calculates and prints the overall `accuracy_score` of the model on the test set.
5.  It generates and prints a `classification_report`, which includes precision, recall, and F1-score for both 'Ham' and 'Spam' classes, providing a more detailed evaluation of the model's performance for each class. The output shows a high overall accuracy and good performance metrics for both classes, although precision and recall are slightly lower for 'Spam' due to the class imbalance.
"""

# Import Naive Bayes and evaluation metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize model
nb_model = MultinomialNB()

# Train model
nb_model.fit(X_train_bow, y_train)

# Predict on test set
y_pred = nb_model.predict(X_test_bow)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Print classification report (Precision, Recall, F1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

"""# Rule-based Keyword Baseline"""

# Simple rule-based baseline
spam_keywords = ["win", "free", "urgent", "claim", "call", "click", "offer", "prize", "congratulations"]

def keyword_baseline_predict(messages):
    preds = []
    for msg in messages:
        msg_lower = msg.lower()
        if any(word in msg_lower for word in spam_keywords):
            preds.append(1)  # Spam
        else:
            preds.append(0)  # Ham
    return preds

# Evaluate baseline
y_pred_baseline = keyword_baseline_predict(X_test)
baseline_acc = accuracy_score(y_test, y_pred_baseline)
print(f"Baseline Keyword Model Accuracy: {baseline_acc * 100:.2f}%")

"""# Confusion Matrix Heatmap of Naive Bayes

This code block visualizes the performance of the Naive Bayes classifier using a confusion matrix heatmap.
1.  It computes the confusion matrix (`cm`) which shows the counts of true positive, true negative, false positive, and false negative predictions.
2.  It uses `seaborn.heatmap` to create a visual representation of the confusion matrix.
3.  `annot=True` displays the counts on the heatmap cells, `fmt='d'` formats the numbers as integers, and `cmap='Blues'` sets the color scheme.
4.  `xticklabels` and `yticklabels` label the axes with 'Ham' and 'Spam' for clarity.
The heatmap provides a clear visual summary of how well the model classified each class and where it made errors (misclassifications). The output shows the number of correctly and incorrectly classified instances for both ham and spam.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot as heatmap
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Ham', 'Spam'], yticklabels=['Ham', 'Spam'])
plt.title('Confusion Matrix - Naive Bayes SMS Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""# Reward-style Learning Curve (Mimics RL Reward Plot)

This code block generates a reward-style learning curve to show how the model's accuracy changes as the amount of training data increases.
1.  It creates a range of `train_sizes` from 10% to 100% of the training data.
2.  It iterates through these sizes, training a new `MultinomialNB` model on a subset of the training data corresponding to the current size.
3.  For each trained model, it evaluates the accuracy on the *full* test set and stores the accuracy score.
4.  Finally, it plots the accuracy scores against the training size percentages.
This plot helps to understand if the model would benefit from more training data or if it has reached a plateau in performance. The output shows a plot where the accuracy generally increases and then stabilizes as more training data is used.
"""

import numpy as np

train_sizes = np.linspace(0.1, 1.0, 10)
accuracy_scores = []

for size in train_sizes:
    X_partial = X_train_bow[:int(size * X_train_bow.shape[0])]
    y_partial = y_train[:int(size * len(y_train))]

    # Train model on partial data
    model_partial = MultinomialNB()
    model_partial.fit(X_partial, y_partial)

    # Evaluate on full test set
    y_pred_partial = model_partial.predict(X_test_bow)
    partial_acc = accuracy_score(y_test, y_pred_partial)
    accuracy_scores.append(partial_acc)

# Plot reward-style accuracy curve
plt.figure(figsize=(6,4))
plt.plot(train_sizes, accuracy_scores, marker='o')
plt.title('Reward-Style Learning Curve (Accuracy vs Training Data Size)')
plt.xlabel('Training Size Percentage')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()

"""# Interpretation of the Reward-Style Learning Curve

The reward-style learning curve shows how the model's accuracy on the test set changes as the amount of training data increases.

**Key Observations:**

* **Initial Improvement:** The accuracy generally increases as more training data is used, especially in the beginning. This indicates that the model benefits from seeing more examples to learn the patterns distinguishing spam from ham.
* **Plateau Effect:** After a certain point (around 40-50% of the training data), the curve starts to flatten out. This suggests that adding significantly more training data beyond this point yields diminishing returns in terms of accuracy improvement for this specific model and dataset.
* **High Final Accuracy:** The curve plateaus at a high accuracy level (close to 98%), which aligns with the results from the classification report and confusion matrix.

**Conclusion:**

The learning curve suggests that the current dataset size is sufficient for the Multinomial Naive Bayes model to achieve its optimal performance on this task. While adding more data initially helps, it's unlikely to lead to substantial accuracy gains beyond what has been observed. Further improvements might require exploring different models or feature engineering techniques rather than simply increasing the dataset size.
"""

from sklearn.metrics import roc_curve, roc_auc_score

# Get probability predictions for the positive class (spam=1)
# Naive Bayes provides log probabilities, so we need to exponentiate
# Alternatively, use predict_proba which is often available
# If using predict_proba, it returns probabilities for both classes, take the positive class (index 1)
y_pred_proba = nb_model.predict_proba(X_test_bow)[:, 1]

# Calculate ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

# Calculate AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_pred_proba)

# Plot the ROC curve
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') # Random guess line
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print(f"AUC (Area Under the ROC Curve): {roc_auc:.2f}")

"""### ROC Curve Report Summary

**What the ROC Curve Shows:** This graph helps to see how well the model can tell the difference between Spam and Ham messages.

**Key Findings:**

*   The blue/orange line (the model's performance) is very close to the top-left corner of the graph.
*   The **Area Under the Curve (AUC)** is 0.99.

**Interpretation:**

*   A high AUC score (close to 1.0) means the model is very good at correctly identifying Spam messages while also doing a good job of not incorrectly flagging Ham messages as Spam.
*   The plot confirms that the model has strong performance in separating the two classes.
"""

from sklearn.metrics import precision_recall_curve, auc

# Get probability predictions for the positive class (spam=1)
# Using the same probabilities calculated for the ROC curve
# y_pred_proba = nb_model.predict_proba(X_test_bow)[:, 1] # Already calculated

# Calculate Precision-Recall curve points
precision, recall, _ = precision_recall_curve(y_test, y_pred_proba)

# Calculate Area Under the Precision-Recall Curve (AUPRC)
auprc = auc(recall, precision)

# Plot the Precision-Recall curve
plt.figure(figsize=(6, 4))
plt.plot(recall, precision, color='darkorange', lw=2, label=f'Precision-Recall curve (AUPRC = {auprc:.2f})')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc="lower left")
plt.grid(True)
plt.show()

print(f"AUPRC (Area Under the Precision-Recall Curve): {auprc:.2f}")

"""# Interpretation of the Precision-Recall Curve

The high AUPRC of 0.98 is excellent. It means your model is very effective at identifying spam messages (good recall) while keeping the number of false alarms (ham messages incorrectly flagged as spam) low (good precision). This is particularly important in your case because spam is the less frequent class. The Precision-Recall curve confirms the strong performance observed with the classification report and confusion matrix, specifically highlighting the model's ability to handle the imbalance and accurately identify the positive class.

# Influence of Preprocessing and Smoothing hyperparameters
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

print("Comparing Model Accuracy with different configurations:")

# --- Configuration 1: With Stop Words and Laplace Smoothing (alpha=1.0) ---
vectorizer_stop = CountVectorizer(stop_words='english')
X_train_stop = vectorizer_stop.fit_transform(X_train)
X_test_stop = vectorizer_stop.transform(X_test)

nb_model_stop_smooth = MultinomialNB(alpha=1.0)
nb_model_stop_smooth.fit(X_train_stop, y_train)
y_pred_stop_smooth = nb_model_stop_smooth.predict(X_test_stop)
accuracy_stop_smooth = accuracy_score(y_test, y_pred_stop_smooth)
print(f"\nConfig 1: With Stop Words, Laplace Smoothing (alpha=1.0) - Accuracy: {accuracy_stop_smooth * 100:.2f}%")

# --- Configuration 2: Without Stop Words and Laplace Smoothing (alpha=1.0) ---
vectorizer_no_stop = CountVectorizer(stop_words=None) # No stop words
X_train_no_stop = vectorizer_no_stop.fit_transform(X_train)
X_test_no_stop = vectorizer_no_stop.transform(X_test)

nb_model_no_stop_smooth = MultinomialNB(alpha=1.0)
nb_model_no_stop_smooth.fit(X_train_no_stop, y_train)
y_pred_no_stop_smooth = nb_model_no_stop_smooth.predict(X_test_no_stop)
accuracy_no_stop_smooth = accuracy_score(y_test, y_pred_no_stop_smooth)
print(f"Config 2: Without Stop Words, Laplace Smoothing (alpha=1.0) - Accuracy: {accuracy_no_stop_smooth * 100:.2f}%")


# --- Configuration 3: With Stop Words and Without Laplace Smoothing (alpha=0) ---
# Use the vectorizer with stop words from Config 1
nb_model_stop_no_smooth = MultinomialNB(alpha=0.0) # No Laplace smoothing
nb_model_stop_no_smooth.fit(X_train_stop, y_train)
y_pred_stop_no_smooth = nb_model_stop_no_smooth.predict(X_test_stop)
accuracy_stop_no_smooth = accuracy_score(y_test, y_pred_stop_no_smooth)
print(f"Config 3: With Stop Words, No Laplace Smoothing (alpha=0.0) - Accuracy: {accuracy_stop_no_smooth * 100:.2f}%")


# --- Configuration 4: Without Stop Words and Without Laplace Smoothing (alpha=0) ---
# Use the vectorizer without stop words from Config 2
nb_model_no_stop_no_smooth = MultinomialNB(alpha=0.0) # No Laplace smoothing
nb_model_no_stop_no_smooth.fit(X_train_no_stop, y_train)
y_pred_no_stop_no_smooth = nb_model_no_stop_no_smooth.predict(X_test_no_stop)
accuracy_no_stop_no_smooth = accuracy_score(y_test, y_pred_no_stop_no_smooth)
print(f"Config 4: Without Stop Words, No Laplace Smoothing (alpha=0.0) - Accuracy: {accuracy_no_stop_no_smooth * 100:.2f}%")

"""# WordCloud for Spam vs Ham

This code block generates WordClouds for both spam and ham messages to visualize the most frequent words in each category.
1.  It concatenates all spam messages into a single string (`spam_text`) and all ham messages into another string (`ham_text`).
2.  It creates a `WordCloud` object for spam text, specifying dimensions and background color.
3.  It generates the word cloud image from the `spam_text`.
4.  It displays the spam word cloud using `matplotlib.pyplot.imshow`, turning off the axis.
5.  It repeats steps 2-4 for the ham text.
The output shows two word clouds: one for spam and one for ham. Larger words in each cloud represent words that appear more frequently in that category of messages. This provides a visual intuition about the key terms that distinguish spam from ham.
"""

from wordcloud import WordCloud

# Separate spam and ham messages
spam_text = " ".join(data[data['label'] == 'spam']['message'])
ham_text = " ".join(data[data['label'] == 'ham']['message'])

# Generate WordCloud for Spam
plt.figure(figsize=(6,4))
wordcloud_spam = WordCloud(width=800, height=400, background_color='white').generate(spam_text)
plt.imshow(wordcloud_spam, interpolation='bilinear')
plt.axis('off')
plt.title('WordCloud - Spam Messages')
plt.show()

# Generate WordCloud for Ham
plt.figure(figsize=(6,4))
wordcloud_ham = WordCloud(width=800, height=400, background_color='white').generate(ham_text)
plt.imshow(wordcloud_ham, interpolation='bilinear')
plt.axis('off')
plt.title('WordCloud - Ham Messages')
plt.show()

"""# Top Keywords in Spam Messages

This code block identifies and visualizes the top 20 most common words found specifically in spam messages after basic text cleaning.
1.  It joins all spam messages into a single string and converts it to lowercase.
2.  It uses regular expressions (`re.findall`) to extract words (sequences of 3 or more letters) from the spam text.
3.  It uses `collections.Counter` to count the frequency of each word and gets the 20 most common ones.
4.  It converts these top words and their counts into a pandas DataFrame for easy plotting.
5.  It generates a horizontal bar plot using `seaborn.barplot` to show the frequency of the top 20 spam words.
The plot highlights the words that are most indicative of spam messages in this dataset, such as 'call', 'free', 'txt', 'mobile', etc.
"""

from collections import Counter
import re

# Get most common words in spam messages
spam_words = " ".join(data[data['label'] == 'spam']['message']).lower()
spam_words = re.findall(r'\b[a-z]{3,}\b', spam_words)  # words with length >= 3
spam_word_freq = Counter(spam_words).most_common(20)

# Convert to DataFrame for plotting
spam_df = pd.DataFrame(spam_word_freq, columns=['word', 'count'])

# Plot
plt.figure(figsize=(8,4))
sns.barplot(x='count', y='word', data=spam_df)
plt.title('Top 20 Most Common Words in Spam Messages')
plt.xlabel('Frequency')
plt.ylabel('Word')
plt.show()

"""## Misclassified Messages (Qualitative Analysis)

Show a few test messages where predictions were incorrect to analyze failure modes.

This code block extracts and displays a sample of messages from the test set that were **misclassified** by the Naive Bayes model.
1.  It creates a copy of the original data rows corresponding to the test set indices.
2.  It adds a 'predicted' column to this new DataFrame with the model's predictions (`y_pred`).
3.  It filters this DataFrame to keep only the rows where the original 'label_encoded' does not match the 'predicted' label.
4.  It prints the first 10 of these misclassified messages, showing the original message, the true label ('ham' or 'spam'), and the model's incorrect prediction (0 or 1).
Examining these misclassified samples helps in understanding the limitations of the model and the types of messages it struggles with, providing insights for potential future improvements.
"""

# Extract misclassified messages safely
misclassified = data.iloc[X_test.index].copy()
misclassified.loc[:, 'predicted'] = y_pred

# Filter only incorrect predictions
misclassified = misclassified[misclassified['label_encoded'] != misclassified['predicted']]

# Display results
print("Sample Misclassified Messages:")
misclassified[['message', 'label', 'predicted']].head(10)

"""# Interpretation of Misclassified Results

During evaluation, several messages were identified as misclassified by the model. For example, legitimate conversational messages such as “Sorry I missed your call let's talk when you...” and “Unlimited texts. Limited minutes.” were incorrectly classified as spam. This suggests that the model is overly sensitive to promotional or alert-style wording, even when the message context is casual or harmless. The phrase “Unlimited texts” resembles typical marketing language, which likely triggered a spam classification despite being a legitimate ham message.

On the other hand, messages like “Latest News! Police station toilet stolen…” and “For sale - arsenal dartboard…” were classified as spam, which might appear unreasonable at first. However, these messages share structural features commonly found in spam, such as unexpected announcements, sensational phrasing, or sale-related terms. Since Naive Bayes relies on word frequency rather than semantic meaning, it flags anything containing “news”, “for sale”, “alert”, or numeric shortcodes like 84484 as potentially spam.

Additionally, security or alert-type phrases such as “You have 1 new message. Please call...” and “Email AlertFrom…” were also marked as spam. These reflect phishing-style patterns that appear frequently in spam emails and SMS phishing campaigns. This indicates that while the classifier is effective at catching promotional and scam-like text, it lacks nuance to differentiate genuine informational alerts from malicious ones.

Overall, this analysis shows that misclassification is not random, but rather pattern-driven, influenced heavily by the model’s bias toward high-frequency spam keywords. This observation supports the need for context-aware enhancements, such as TF-IDF weighting or more advanced models like Logistic Regression or Transformers to capture intent rather than just keyword presence.

# DEMO

This code block provides a simple interactive demonstration of the trained Naive Bayes model.
1.  It defines a list of `user_messages` containing new, custom text messages.
2.  It transforms these `user_messages` into Bag-of-Words vectors using the *same* `vectorizer` fitted during preprocessing.
3.  It uses the trained `nb_model` to predict whether each `user_vectors` is spam or ham.
4.  It iterates through the original user messages and their corresponding predictions, printing each message along with its predicted label ('Spam' or 'Ham').
This allows you to input your own messages and see how the model classifies them in real-time, demonstrating its practical application.
"""

# Test with your own custom messages
user_messages = [
    "Congratulations! You've won a free vacation. Click here to claim.",
    "Are we still meeting tomorrow at 6?",
    "click on this link to win $10000",
    "Congrats! Your phone number just won a $1,000 gift card! Reply 'CASH' to accept now before it expires.",
    "URGENT: Your account will be suspended unless you verify now!",
    "Let's catch up later, it's been a while!",
    "Hey, are we still on for dinner tonight at 7? Let me know if you can make it",
    "Meeting canceled. Will reschedule for next week. Check the calendar invite for updates.",
    "Your one-time security code is 882103. Do not share this code with anyone.",
    "Can you send me the notes from class? I missed the first half hour.",
    "The concert is delayed due to heavy rain. Check the venue app for the new start time.",
    "URGENT: Your bank account has been suspended due to unauthorized activity. Verify your details here immediately: http://secure.acct-fix.co",

]

# Convert using same vectorizer
user_vectors = vectorizer.transform(user_messages)

# Predict
user_preds = nb_model.predict(user_vectors)

# Display results
print(" Live Spam Detection Test:")
for msg, pred in zip(user_messages, user_preds):
    label = "Spam" if pred == 1 else "Ham"
    print(f"Message: \"{msg}\"  -->  Prediction: {label}")

"""# Misclassification Observation — OTP Message

One interesting misclassification observed during real-world testing involved a legitimate OTP (One-Time Password) message:
“Your one-time security code is 882103. Do not share this code with anyone.”
The model incorrectly classified this message as spam. This behavior can be explained by the way Naive Bayes relies on word frequency patterns rather than contextual understanding. Words and phrases such as “security code”, “Do not share”, and the presence of six-digit numeric patterns are commonly found in phishing and fraudulent spam messages in the training dataset. As a result, the model associated these features with a high probability of spam, despite the message being a legitimate security notification.

# Conclusion

In this project, a Naive Bayes classifier was successfully implemented to detect SMS spam messages using a Bag-of-Words feature representation. The model achieved high accuracy and demonstrated strong performance as shown by the confusion matrix and reward-style learning curve. Visual insights such as WordClouds and keyword frequency analysis further revealed the language patterns characteristic of spam messages. Overall, this project demonstrates that even with a simple probabilistic model, effective spam detection can be achieved with minimal computational resources. Future improvements could include experimenting with TF-IDF weighting, deep learning models, or ensemble techniques for enhanced performance.
"""